name: EconomyGamble
main: MakerbakerYT\EconomyGamble
version: 2.0-alpha
author: MakerbakerYT
api: [3.14.0, 4.0.0]

commands:
 gamblehow:
  permission: EconomyGamble.commands.gamblehow
  description: EconomyGamble Helper
  usage: /gamblehow

permissions:
 EconomyGamble.commands.*:
  default: true
  description: Allows commands of EconomyGamble
